from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.enums import TA_CENTER


def generate_report(
    filename,
    community_id,
    risk,
    members,
    shared_devices,
    avg_age,
    reasons,
    savings
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    story = []

    story.append(
        Paragraph("FraudNet Investigation Report", title)
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "<b>Executive Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"Community {community_id} has been identified as a high-risk coordinated fraud cluster.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,15))

    story.append(
        Paragraph(
            "<b>Evidence</b>",
            styles["Heading2"]
        )
    )

    bullets = [
        f"Risk Score: {risk}/100",
        f"Connected Accounts: {members}",
        f"Shared Devices: {shared_devices}",
        f"Average Account Age: {avg_age} days",
        f"Estimated Merchant Savings: ₹{savings:,}"
    ]

    for item in bullets:
        story.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    story.append(Spacer(1,15))

    story.append(
        Paragraph(
            "<b>Why FraudNet Flagged This</b>",
            styles["Heading2"]
        )
    )

    for reason in reasons.split(", "):
        story.append(
            Paragraph(f"• {reason}", styles["BodyText"])
        )

    story.append(Spacer(1,15))

    story.append(
        Paragraph(
            "<b>Recommended Action</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            "Pause automatic refunds for this community and perform manual verification before approving additional refunds.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "Generated by FraudNet AI Risk Manager",
            styles["Italic"]
        )
    )

    doc.build(story)